AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 instance - Ubuntu 24.04, t3.medium, 8GB gp3

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair for SSH access
    Default: ec2-key

  InstanceType:
    Type: String
    Default: t3.medium
    Description: EC2 instance type

  VolumeSize:
    Type: Number
    Default: 8
    Description: Root volume size in GB

  SSHCidr:
    Type: String
    Default: 0.0.0.0/0
    Description: CIDR block allowed for SSH access
    AllowedPattern: '(\d{1,3}\.){3}\d{1,3}/\d{1,2}'

  InstanceName:
    Type: String
    Default: my-server
    Description: Name tag for the EC2 instance

  UbuntuAMI:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/canonical/ubuntu/server/24.04/stable/current/amd64/hvm/ebs-gp3/ami-id
    Description: Latest Ubuntu 24.04 AMI from SSM Parameter Store

Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SSH access for EC2 instance
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref SSHCidr
      Tags:
        - Key: Name
          Value: !Sub '${InstanceName}-sg'

  Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: !Ref UbuntuAMI
      SecurityGroupIds:
        - !GetAtt SecurityGroup.GroupId
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: !Ref VolumeSize
            VolumeType: gp3
            DeleteOnTermination: true
      Tags:
        - Key: Name
          Value: !Ref InstanceName

Outputs:
  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref Instance

  PublicIP:
    Description: Public IP address
    Value: !GetAtt Instance.PublicIp

  SSHCommand:
    Description: SSH command to connect
    Value: !Sub 'ssh -i ${KeyName}.pem ubuntu@${Instance.PublicIp}'